/*
================================================
  CUSTOMER SHOPPING BEHAVIOUR
  SQL Analysis Queries
  Tool: PostgreSQL
  Author: Masooma Rizvi
  Date: June 2025
================================================
*/


/*------------------------------------------------
  TABLE SETUP
------------------------------------------------*/

CREATE TABLE customer (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(10),
    item_purchased VARCHAR(50),
    category VARCHAR(20),
    purchase_amount NUMERIC(6,2),
    location VARCHAR(50),
    size VARCHAR(5),
    color VARCHAR(30),
    season VARCHAR(10),
    review_rating VARCHAR(5),
    subscription_status VARCHAR(5),
    shipping_type VARCHAR(20),
    discount_applied VARCHAR(5),
    promo_code_used VARCHAR(5),
    previous_purchases INT,
    payment_method VARCHAR(20),
    frequency_of_purchases VARCHAR(20)
);

COPY customer(customer_id, age, gender, item_purchased, category, purchase_amount,
    location, size, color, season, review_rating, subscription_status, shipping_type,
    discount_applied, promo_code_used, previous_purchases, payment_method, frequency_of_purchases)
FROM '/your/path/customer_shopping_behavior.csv'
DELIMITER ','
CSV HEADER;

-- Add age_group column used in revenue analysis
ALTER TABLE customer ADD COLUMN age_group VARCHAR(20);

UPDATE customer SET age_group =
    CASE
        WHEN age < 25 THEN 'Young Adult'
        WHEN age BETWEEN 25 AND 39 THEN 'Adult'
        WHEN age BETWEEN 40 AND 54 THEN 'Middle-aged'
        ELSE 'Senior'
    END;


/*------------------------------------------------
  SECTION 1 — REVENUE & DEMOGRAPHICS
------------------------------------------------*/

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


/*------------------------------------------------
  SECTION 2 — PRODUCT & CATEGORY PERFORMANCE
------------------------------------------------*/

-- Q3. Which are the top 5 products with the highest average review ratings?
SELECT item_purchased,
    ROUND(AVG(review_rating::numeric), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q12. What are the top 5 most purchased products?
SELECT item_purchased, COUNT(customer_id) AS total_orders
FROM customer
GROUP BY item_purchased
ORDER BY total_orders DESC
LIMIT 5;


-- Q13. What are the bottom 5 least purchased products?
SELECT item_purchased, COUNT(customer_id) AS total_orders
FROM customer
GROUP BY item_purchased
ORDER BY total_orders ASC
LIMIT 5;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q11. What is the top selling product in each category?
WITH ranked_items AS (
    SELECT category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders
FROM ranked_items
WHERE rank = 1
ORDER BY total_orders DESC;


/*------------------------------------------------
  SECTION 3 — SUBSCRIPTIONS & CUSTOMER LOYALTY
------------------------------------------------*/

-- Q5. Do subscribed customers spend more?
--     Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases
--     New = 1 purchase | Returning = 2-10 purchases | Loyal = 11+ purchases
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyer
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


/*------------------------------------------------
  SECTION 4 — DISCOUNTS, SHIPPING & SPEND PATTERNS
------------------------------------------------*/

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100,
    2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard and Express shipping
SELECT shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
